language: node_js
node_js:
- '12'
before_script:
- yarn install
script: yarn run build
deploy:
  skip_cleanup: true
  provider: npm
  api_key: $NPM_TOKEN
  email: a.golovchuk@gmail.com
  on:
    tags: true
  branch: master